/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backup.Manage_ReservasiDea;
import Backup.Manage_PesawatDea;
import Backup.Manage_CustomersDea;
import Backup.Manage_AdminDea;
import java.awt.Color;

/**
 *
 * @author WINDOWS 10
 */
public class Dashboard_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Dasboard
     */
    public Dashboard_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageAdmin = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        btnManagePesawat = new javax.swing.JButton();
        btnManageReservasi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 167, 218));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Dashboard Admin");

        btnManageAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnManageAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnManageAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_menu.png"))); // NOI18N
        btnManageAdmin.setText("  Manage Admin");
        btnManageAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageAdminMouseExited(evt);
            }
        });
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });

        btnManageCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageCustomers.setForeground(new java.awt.Color(51, 51, 51));
        btnManageCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer_menu.png"))); // NOI18N
        btnManageCustomers.setText(" Manage Customer");
        btnManageCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageCustomersMouseExited(evt);
            }
        });
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });

        btnManagePesawat.setBackground(new java.awt.Color(255, 255, 255));
        btnManagePesawat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManagePesawat.setForeground(new java.awt.Color(51, 51, 51));
        btnManagePesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pesawat_menu.png"))); // NOI18N
        btnManagePesawat.setText("   Manage Flights");
        btnManagePesawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManagePesawatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManagePesawatMouseExited(evt);
            }
        });
        btnManagePesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePesawatActionPerformed(evt);
            }
        });

        btnManageReservasi.setBackground(new java.awt.Color(255, 255, 255));
        btnManageReservasi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageReservasi.setForeground(new java.awt.Color(51, 51, 51));
        btnManageReservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reservation_menu.png"))); // NOI18N
        btnManageReservasi.setText("  Manage Reservasi");
        btnManageReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageReservasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageReservasiMouseExited(evt);
            }
        });
        btnManageReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReservasiActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_utama.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManagePesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(303, 303, 303))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        Manage_Admin ang = new Manage_Admin();
        ang.setVisible(true);
        ang.pack();
        ang.setLocationRelativeTo(null);
        ang.setDefaultCloseOperation(Dashboard_Admin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void btnManageReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReservasiActionPerformed
        Manage_Reservasi ang = new Manage_Reservasi();
        ang.setVisible(true);
        ang.pack();
        ang.setLocationRelativeTo(null);
        ang.setDefaultCloseOperation(Dashboard_Admin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnManageReservasiActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        Manage_Customer ang = new Manage_Customer();
        ang.setVisible(true);
        ang.pack();
        ang.setLocationRelativeTo(null);
        ang.setDefaultCloseOperation(Dashboard_Admin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnManagePesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePesawatActionPerformed
        Manage_Penerbangan ang = new Manage_Penerbangan();
        ang.setVisible(true);
        ang.pack();
        ang.setLocationRelativeTo(null);
        ang.setDefaultCloseOperation(Dashboard_Admin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnManagePesawatActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login_Admin ang = new Login_Admin();
        ang.setVisible(true);
        ang.pack();
        ang.setLocationRelativeTo(null);
        ang.setDefaultCloseOperation(Dashboard_Admin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCustomersMouseEntered
        btnManageCustomers.setBackground(Color.yellow);
    }//GEN-LAST:event_btnManageCustomersMouseEntered

    private void btnManageCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCustomersMouseExited
       btnManageCustomers.setBackground(Color.white);
    }//GEN-LAST:event_btnManageCustomersMouseExited

    private void btnManageAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageAdminMouseEntered
        btnManageAdmin.setBackground(Color.yellow);
    }//GEN-LAST:event_btnManageAdminMouseEntered

    private void btnManageAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageAdminMouseExited
        btnManageAdmin.setBackground(Color.white);
    }//GEN-LAST:event_btnManageAdminMouseExited

    private void btnManagePesawatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePesawatMouseEntered
         btnManagePesawat.setBackground(Color.yellow);
    }//GEN-LAST:event_btnManagePesawatMouseEntered

    private void btnManagePesawatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePesawatMouseExited
       btnManagePesawat.setBackground(Color.white);
    }//GEN-LAST:event_btnManagePesawatMouseExited

    private void btnManageReservasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageReservasiMouseEntered
         btnManageReservasi.setBackground(Color.yellow);
    }//GEN-LAST:event_btnManageReservasiMouseEntered

    private void btnManageReservasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageReservasiMouseExited
        btnManageReservasi.setBackground(Color.white);
    }//GEN-LAST:event_btnManageReservasiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManagePesawat;
    private javax.swing.JButton btnManageReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
